-- database lab on 17/10/2022
-- learning select, update, delete, alter clauses

select first_name || ' '|| last_name as "Name" from employees;
select first_name, salary, salary*12 "Salary per year" from employees;
select distinct job_id from employees;
-- copy table together w/ constraints
create table EMP as select * from employees;

CREATE TABLE members(
    member_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    PRIMARY KEY(member_id)
);
ALTER TABLE members
ADD birth_date DATE NOT NULL;
